server:
  port: 8082

spring:
  application:
    name: icecream-orders-consumer
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    kafka:
      template:
        default-topic: ice-cream-orders
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: icecream-orders-listener-group
      auto-offset-reset: latest
    properties:
      schema.registry.url : http://localhost:8081